sonar.projectKey=dndudchl_a2-front
sonar.organization=dndudchl

# Source code locations
sonar.sources=.

# Coverage report paths
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8

