sonar.projectName=a2
sonar.projectVersion=1.0

sonar.projectKey=dndudchl_a2-front
sonar.organization=dndudchl

# Source code locations
sonar.sources=.

# Coverage report paths
sonar.javascript.lcov.reportPaths=coverage/lcov.info

# Encoding
sonar.sourceEncoding=UTF-8







# Path is relative to the sonar-project.properties file. Replace "\" by "/" on Windows.
#sonar.sources=.

# Encoding of the source code. Default is default system encoding
#sonar.sourceEncoding=UTF-8
